---
Name: sortablefile
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'dia-nz/sortablefile: client/dist/styles/main.css'
  extra_requirements_javascript:
    - 'dia-nz/sortablefile: client/dist/js/main.js'
